name: pdf_reader_manager
description: A comprehensive PDF management and editing application with advanced tools.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.0
  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.5
  path: ^1.8.3
  permission_handler: ^11.0.1
  device_info_plus: ^11.3.0
  share_plus: ^7.0.0
  url_launcher: ^6.2.0
  image_picker: ^1.0.4
  printing: ^5.11.0
  open_file: ^3.3.3
  flutter_email_sender: ^8.0.0
  connectivity_plus: ^5.0.0
  cached_network_image: ^3.3.0
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    # --- YENİ kutuphaneler ve lang.js ---
    - assets/web/lang.js
    - assets/web/franc.min.js
    - assets/web/pdf-lib.min.js
    - assets/web/pdf.min.js
    - assets/web/tesseract.min.js
    
    # --- YENİ TOOLS HTML DOSYALARI ---
    - assets/web/birlestirme.html
    - assets/web/imza.html
    - assets/web/res_pdf.html
    - assets/web/pdf_resim_ekle.html
    - assets/web/sesli_okuma.html
    - assets/web/ocr.html
    - assets/web/pdf_res.html
    - assets/web/pdf_metin_ekle.html
    - assets/web/organize.html
    - assets/web/sikistirma.html

    # PDFjs zorunlu dosyalari
    - assets/build/pdf.mjs
    - assets/build/pdf.worker.mjs
    - assets/web/viewer.css
    - assets/web/viewer.html
    - assets/web/viewer.mjs
    - assets/web/images/
    - assets/icon/
    - assets/icon/logo.png
    - assets/icon/drive.png
    - assets/icon/onedrive.png
    - assets/icon/dropbox.png
    - assets/icon/gmail.png
    - assets/web/locale/locale.json
    - assets/web/locale/af/
    - assets/web/locale/an/
    - assets/web/locale/ar/
    - assets/web/locale/az/
    - assets/web/locale/be/
    - assets/web/locale/bg/
    - assets/web/locale/bn/
    - assets/web/locale/bo/
    - assets/web/locale/br/
    - assets/web/locale/bs/
    - assets/web/locale/ca/
    - assets/web/locale/cak/
    - assets/web/locale/cs/
    - assets/web/locale/cy/
    - assets/web/locale/da/
    - assets/web/locale/de/
    - assets/web/locale/dsb/
    - assets/web/locale/el/
    - assets/web/locale/en-CA/
    - assets/web/locale/en-GB/
    - assets/web/locale/en-US/
    - assets/web/locale/es-AR/
    - assets/web/locale/es-CL/
    - assets/web/locale/es-ES/
    - assets/web/locale/es-MX/
    - assets/web/locale/et/
    - assets/web/locale/eu/
    - assets/web/locale/fa/
    - assets/web/locale/ff/
    - assets/web/locale/fi/
    - assets/web/locale/fr/
    - assets/web/locale/fy-NL/
    - assets/web/locale/ga-IE/
    - assets/web/locale/gl/
    - assets/web/locale/gn/
    - assets/web/locale/hi-IN/
    - assets/web/locale/hr/
    - assets/web/locale/hsb/
    - assets/web/locale/hu/
    - assets/web/locale/hy-AM/
    - assets/web/locale/id/
    - assets/web/locale/is/
    - assets/web/locale/it/
    - assets/web/locale/ja/
    - assets/web/locale/kk/
    - assets/web/locale/km/
    - assets/web/locale/kn/
    - assets/web/locale/ko/
    - assets/web/locale/lo/
    - assets/web/locale/lt/
    - assets/web/locale/lv/
    - assets/web/locale/meh/
    - assets/web/locale/mk/
    - assets/web/locale/ml/
    - assets/web/locale/mr/
    - assets/web/locale/ms/
    - assets/web/locale/my/
    - assets/web/locale/nb-NO/
    - assets/web/locale/ne-NP/
    - assets/web/locale/nn-NO/
    - assets/web/locale/oc/
    - assets/web/locale/pa-IN/
    - assets/web/locale/pl/
    - assets/web/locale/pt-BR/
    - assets/web/locale/pt-PT/
    - assets/web/locale/ro/
    - assets/web/locale/ru/
    - assets/web/locale/sat/
    - assets/web/locale/scn/
    - assets/web/locale/sco/
    - assets/web/locale/sk/
    - assets/web/locale/sl/
    - assets/web/locale/sq/
    - assets/web/locale/sr/
    - assets/web/locale/sv-SE/
    - assets/web/locale/ta/
    - assets/web/locale/te/
    - assets/web/locale/tg/
    - assets/web/locale/th/
    - assets/web/locale/tr/
    - assets/web/locale/uk/
    - assets/web/locale/ur/
    - assets/web/locale/uz/
    - assets/web/locale/vi/
    - assets/web/locale/zh-CN/
    - assets/web/locale/zh-TW/
