name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo bo≈ü bile olsa checkout gereklidir
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Template indir
      - name: Download Capacitor Remix Template
        run: |
          curl -L https://github.com/ionic-team/capacitor-remix-templates/archive/refs/heads/main.zip -o template.zip
          unzip template.zip -d template
          mv template/capacitor-remix-templates-main project
          rm template.zip

      # Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # npm install
      - name: Install Dependencies
        run: |
          cd project
          npm install

      # cap sync android
      - name: Capacitor Sync Android
        run: |
          cd project
          npx cap sync android

      # Debug APK build
      - name: Build Debug APK
        run: |
          cd project/android
          chmod +x gradlew
          ./gradlew assembleDebug

      # APK artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: project/android/app/build/outputs/apk/debug/app-debug.apk
